### ISSUE TITLE
How to transform the core's interface to pcs's VLs?

### ISSUE THREAD

**Issue by Jzone315** [lewiz-support/LMAC_CORE3#1]
Hi:
    I am trying to design a 100g pcs  block(4x25G mode) interconnected with this core, but there were some questions confused me, so i am hoping to get some helps from you, thanks a lot.
    According to the core's user manual, i got the 100G mac core's interface is 390.625Mhz with 256bits, so i considered it as four lanes of CGMII interfaces(4x64bits), but in the pcs design, i have learned that after the 64b66b and scramble blocks, there will be a 20 VLs(virtual lanes), for most uses, the transform of the VLs is 10->20->10->4, but in the LMAC core, the design lanes of the CGMII interface is already four, so i want to now to transform these fours lanes interfaces to VLs, was it 4->10->20->10->4, or just 4->20->10->4, or others?
   Thanks again, i am looking forward to your reply.

**Comment by lewiz-support** [comment]
Sorry, we did not see your question earlier. It looks like you figured this out.
Please keep us updated on your PCS design. It's an area of interest to us.
